name = "Counter"
license = "Unlicense"
licenselink = "https://unlicense.org"
description = "Small and elegant Hugo theme"

homepage = "https://github.com/tokenicrat/hugo-theme-counter"

demosite = "https://blog.bytoken.link"

tags = ["blog", "minimal"]
features = ["katex"]

[author]
    name = "Tokenicrat"
    homepage = "https://github.com/tokenicrat"
