name = 'Counter'
license = 'The Unlicense'
licenselink = 'https://github.com/tokenicrat/hugo-theme-counter/blob/main/LICENSE'
description = '计数器 | 「词元计数器」的 Hugo 主题'

homepage = 'https://github.com/tokenicrat/hugo-theme-counter'
demosite = 'https://hugo-theme-counter.pages.dev/'

tags = ['blog', 'minimal', 'fast']
features = [
  'dark-mode', 
  'customizable', 
  'search', 
  'katex',
  'mermaid'
]

[author]
  name = 'Tokenicrat'
  homepage = 'https://hi.tokenisite.top/'
